-- =============================================
-- FULL LMS SCHEMA (FACTORY READY)
-- =============================================

-- 1. Courses (The main container)
create table if not exists public.courses (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  description text,
  thumbnail_url text,
  resource_id uuid references public.learning_resources(id), -- Link to the source book
  category text,
  published boolean default false,
  
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 2. Modules (Sections within a course)
create table if not exists public.modules (
  id uuid default gen_random_uuid() primary key,
  course_id uuid references public.courses(id) on delete cascade not null,
  title text not null,
  description text,
  order_index integer default 0,
  
  created_at timestamptz default now()
);

-- 3. Lessons (The actual content)
create table if not exists public.lessons (
  id uuid default gen_random_uuid() primary key,
  module_id uuid references public.modules(id) on delete cascade not null,
  title text not null,
  content text, -- Markdown content generated by Nemotron
  video_url text, -- Optional
  duration_minutes integer,
  order_index integer default 0,
  
  created_at timestamptz default now()
);

-- 4. Quizzes
create table if not exists public.quizzes (
  id uuid default gen_random_uuid() primary key,
  module_id uuid references public.modules(id) on delete cascade,
  course_id uuid references public.courses(id) on delete cascade, -- Optional shortcut
  title text not null,
  
  created_at timestamptz default now()
);

-- 5. Questions
create table if not exists public.questions (
  id uuid default gen_random_uuid() primary key,
  quiz_id uuid references public.quizzes(id) on delete cascade not null,
  text text not null,
  options jsonb, -- Array of strings ["A", "B", "C", "D"]
  correct_answer text, -- The correct string
  explanation text, -- Why it is correct
  
  created_at timestamptz default now()
);

-- Enable RLS
alter table public.courses enable row level security;
alter table public.modules enable row level security;
alter table public.lessons enable row level security;
alter table public.quizzes enable row level security;
alter table public.questions enable row level security;

-- Policies (Public Read, Admin Write)
create policy "Public Read Courses" on public.courses for select using (true);
create policy "Public Read Modules" on public.modules for select using (true);
create policy "Public Read Lessons" on public.lessons for select using (true);
create policy "Public Read Quizzes" on public.quizzes for select using (true);
create policy "Public Read Questions" on public.questions for select using (true);

-- Admin Write (Service Role or Admin User)
-- For simplicity, we assume Service Role bypasses RLS, but if using client:
create policy "Admin Manage Courses" on public.courses for all using (
  exists (select 1 from public.admins where user_id = auth.uid())
);
-- Repeat for others...
