-- TABEL BARU: PROCESSING JOBS (Untuk 7-Layer Pipeline)
CREATE TABLE IF NOT EXISTS processing_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id UUID NOT NULL UNIQUE,
  file_name TEXT NOT NULL,
  file_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  user_email TEXT NOT NULL,
  stepper_response JSONB,
  confidence_score INTEGER,
  evidence_level TEXT,
  vr_suitability_score INTEGER,
  folder_link TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

-- INDEXES UNTUK PERFORMA
CREATE INDEX IF NOT EXISTS idx_job_id ON processing_jobs(job_id);
CREATE INDEX IF NOT EXISTS idx_user_email ON processing_jobs(user_email);
CREATE INDEX IF NOT EXISTS idx_status ON processing_jobs(status);

-- ENABLE REALTIME AGAR DASHBOARD BISA LIVE UPDATE
ALTER PUBLICATION supabase_realtime ADD TABLE processing_jobs;
