/**
 * Seed Data — Alumni Profiles
 * 20 realistic alumni profiles for Teknik Mesin ITS
 */

import type { AlumniProfile } from './types';

type SeedAlumni = Omit<AlumniProfile, 'id' | 'created_at' | 'updated_at' | 'is_active' | 'fts'>;

export const SEED_ALUMNI: SeedAlumni[] = [
    {
        name: 'Dr. Andi Prasetyo',
        angkatan: '2010',
        department: 'Teknik Mesin',
        degree: 'S3',
        job_title: 'Senior Research Engineer',
        company: 'PT Toyota Motor Manufacturing Indonesia',
        industry: 'Otomotif',
        city: 'Jakarta',
        country: 'Indonesia',
        linkedin_url: null,
        email: null,
        phone: null,
        bio: 'Menyelesaikan S3 di Tohoku University. Fokus pada pengembangan mesin hybrid dan kontrol emisi.',
        skills: ['Powertrain', 'CFD', 'ProEngineer', 'MATLAB'],
        is_mentor: true,
        mentor_topics: ['Karir di Otomotif', 'Riset S3 di Jepang'],
        photo_url: null,
        source: 'seed',
    },
    {
        name: 'Sari Wulandari, M.T.',
        angkatan: '2014',
        department: 'Teknik Mesin',
        degree: 'S2',
        job_title: 'Production Manager',
        company: 'PT Astra Honda Motor',
        industry: 'Manufaktur',
        city: 'Karawang',
        country: 'Indonesia',
        linkedin_url: null,
        email: null,
        phone: null,
        bio: 'Spesialis lean manufacturing dan Six Sigma. Black Belt certified.',
        skills: ['Lean Manufacturing', 'Six Sigma', 'AutoCAD', 'SAP'],
        is_mentor: true,
        mentor_topics: ['Lean Manufacturing', 'Karir Perempuan di Industri'],
        photo_url: null,
        source: 'seed',
    },
    {
        name: 'Budi Hartono',
        angkatan: '2016',
        department: 'Teknik Mesin',
        degree: 'S1',
        job_title: 'Mechanical Design Engineer',
        company: 'PT Pertamina (Persero)',
        industry: 'Minyak & Gas',
        city: 'Balikpapan',
        country: 'Indonesia',
        linkedin_url: null,
        email: null,
        phone: null,
        bio: 'Desain dan maintenance peralatan kilang minyak. Berpengalaman dalam piping design.',
        skills: ['Piping Design', 'ASME', 'CAESAR II', 'SolidWorks'],
        is_mentor: false,
        mentor_topics: [],
        photo_url: null,
        source: 'seed',
    },
    {
        name: 'Ratna Dewi',
        angkatan: '2015',
        department: 'Teknik Mesin',
        degree: 'S2',
        job_title: 'Co-Founder & CTO',
        company: 'GreenTech Solutions',
        industry: 'Energi Terbarukan',
        city: 'Surabaya',
        country: 'Indonesia',
        linkedin_url: null,
        email: null,
        phone: null,
        bio: 'Mendirikan startup energi surya setelah lulus S2 dari TU Delft. Fokus pada solar panel optimization.',
        skills: ['Solar Energy', 'Business Development', 'Python', 'Data Analysis'],
        is_mentor: true,
        mentor_topics: ['Entrepreneurship', 'Energi Terbarukan', 'Studi di Belanda'],
        photo_url: null,
        source: 'seed',
    },
    {
        name: 'Irfan Hakim',
        angkatan: '2013',
        department: 'Teknik Mesin',
        degree: 'S1',
        job_title: 'Senior Consultant',
        company: 'McKinsey & Company',
        industry: 'Konsultan Manajemen',
        city: 'Singapore',
        country: 'Singapore',
        linkedin_url: null,
        email: null,
        phone: null,
        bio: 'Transisi dari engineer ke konsultan. Spesialis operasi dan supply chain di sektor industri.',
        skills: ['Operations', 'Supply Chain', 'Data Analytics', 'Strategy'],
        is_mentor: true,
        mentor_topics: ['Karir di Konsultan', 'Kerja di Luar Negeri'],
        photo_url: null,
        source: 'seed',
    },
    {
        name: 'Fajar Nugroho',
        angkatan: '2017',
        department: 'Teknik Mesin',
        degree: 'S1',
        job_title: 'Robotics Engineer',
        company: 'PT ABB Indonesia',
        industry: 'Otomasi Industri',
        city: 'Cikarang',
        country: 'Indonesia',
        linkedin_url: null,
        email: null,
        phone: null,
        bio: 'Fokus pada industrial robotics dan PLC programming. Aktif di komunitas robotika Indonesia.',
        skills: ['Robotics', 'PLC', 'ROS', 'C++', 'Arduino'],
        is_mentor: false,
        mentor_topics: [],
        photo_url: null,
        source: 'seed',
    },
    {
        name: 'Diana Putri, M.Eng.',
        angkatan: '2012',
        department: 'Teknik Mesin',
        degree: 'S2',
        job_title: 'Quality Assurance Manager',
        company: 'PT Unilever Indonesia',
        industry: 'FMCG',
        city: 'Cikarang',
        country: 'Indonesia',
        linkedin_url: null,
        email: null,
        phone: null,
        bio: 'Pakar quality management system. ISO 9001 & 14001 Lead Auditor.',
        skills: ['QMS', 'ISO 9001', 'Statistical Process Control', 'Root Cause Analysis'],
        is_mentor: true,
        mentor_topics: ['Quality Management', 'Karir di FMCG'],
        photo_url: null,
        source: 'seed',
    },
    {
        name: 'Reza Firmansyah',
        angkatan: '2018',
        department: 'Teknik Mesin',
        degree: 'S1',
        job_title: 'Data Engineer',
        company: 'Tokopedia',
        industry: 'Teknologi',
        city: 'Jakarta',
        country: 'Indonesia',
        linkedin_url: null,
        email: null,
        phone: null,
        bio: 'Beralih ke tech industry setelah lulus. Self-taught programmer yang kini mengelola data pipeline skala besar.',
        skills: ['Python', 'SQL', 'Apache Spark', 'AWS', 'Docker'],
        is_mentor: true,
        mentor_topics: ['Transisi ke Tech', 'Data Engineering'],
        photo_url: null,
        source: 'seed',
    },
    {
        name: 'Hendra Kusuma',
        angkatan: '2011',
        department: 'Teknik Mesin',
        degree: 'S2',
        job_title: 'Plant Manager',
        company: 'PT Semen Indonesia',
        industry: 'Konstruksi Material',
        city: 'Gresik',
        country: 'Indonesia',
        linkedin_url: null,
        email: null,
        phone: null,
        bio: '12 tahun pengalaman di industri semen. Mengelola operasi pabrik dengan 500+ karyawan.',
        skills: ['Plant Management', 'Maintenance', 'Project Management', 'HSE'],
        is_mentor: true,
        mentor_topics: ['Manajemen Pabrik', 'Leadership'],
        photo_url: null,
        source: 'seed',
    },
    {
        name: 'Lina Marlina',
        angkatan: '2019',
        department: 'Teknik Mesin',
        degree: 'S1',
        job_title: 'Product Design Engineer',
        company: 'Dyson',
        industry: 'Consumer Electronics',
        city: 'Singapore',
        country: 'Singapore',
        linkedin_url: null,
        email: null,
        phone: null,
        bio: 'Merancang produk consumer electronics di salah satu perusahaan inovasi terdepan dunia.',
        skills: ['Product Design', 'SolidWorks', 'FEA', 'Prototyping', 'DFM'],
        is_mentor: false,
        mentor_topics: [],
        photo_url: null,
        source: 'seed',
    },
    {
        name: 'Ahmad Rizal',
        angkatan: '2016',
        department: 'Teknik Mesin',
        degree: 'S1',
        job_title: 'Maintenance Reliability Engineer',
        company: 'PT PLN (Persero)',
        industry: 'Energi',
        city: 'Surabaya',
        country: 'Indonesia',
        linkedin_url: null,
        email: null,
        phone: null,
        bio: 'Spesialis reliability-centered maintenance untuk turbin pembangkit listrik.',
        skills: ['RCM', 'Vibration Analysis', 'Thermography', 'CMMS'],
        is_mentor: false,
        mentor_topics: [],
        photo_url: null,
        source: 'seed',
    },
    {
        name: 'Yusuf Maulana',
        angkatan: '2014',
        department: 'Teknik Mesin',
        degree: 'S2',
        job_title: 'Dosen & Peneliti',
        company: 'ITS Surabaya',
        industry: 'Pendidikan',
        city: 'Surabaya',
        country: 'Indonesia',
        linkedin_url: null,
        email: null,
        phone: null,
        bio: 'Dosen muda di Departemen Teknik Mesin ITS. Riset di bidang computational mechanics.',
        skills: ['FEM', 'ANSYS', 'Research', 'Teaching', 'Scientific Writing'],
        is_mentor: true,
        mentor_topics: ['Karir Akademik', 'Riset S2/S3'],
        photo_url: null,
        source: 'seed',
    },
    {
        name: 'Putri Amelia',
        angkatan: '2018',
        department: 'Teknik Mesin',
        degree: 'S1',
        job_title: 'Process Engineer',
        company: 'PT Chevron Pacific Indonesia',
        industry: 'Minyak & Gas',
        city: 'Riau',
        country: 'Indonesia',
        linkedin_url: null,
        email: null,
        phone: null,
        bio: 'Process engineer di operasi upstream oil & gas. Berpengalaman dalam process simulation.',
        skills: ['HYSYS', 'Process Simulation', 'PFD/P&ID', 'Project Economics'],
        is_mentor: false,
        mentor_topics: [],
        photo_url: null,
        source: 'seed',
    },
    {
        name: 'Denny Setiawan',
        angkatan: '2013',
        department: 'Teknik Mesin',
        degree: 'S1',
        job_title: 'Co-Founder',
        company: 'MesinKita.com',
        industry: 'E-Commerce B2B',
        city: 'Surabaya',
        country: 'Indonesia',
        linkedin_url: null,
        email: null,
        phone: null,
        bio: 'Membangun marketplace B2B untuk spare part dan mesin industri. Alumnus YCAB Foundation.',
        skills: ['Entrepreneurship', 'Business Strategy', 'Product Management', 'Mechanical Parts'],
        is_mentor: true,
        mentor_topics: ['Startup', 'E-Commerce', 'Fundraising'],
        photo_url: null,
        source: 'seed',
    },
    {
        name: 'Wahyu Hidayat',
        angkatan: '2020',
        department: 'Teknik Mesin',
        degree: 'S1',
        job_title: 'Graduate Trainee',
        company: 'PT Astra International',
        industry: 'Konglomerat',
        city: 'Jakarta',
        country: 'Indonesia',
        linkedin_url: null,
        email: null,
        phone: null,
        bio: 'Fresh graduate yang mengikuti program management trainee di Astra International.',
        skills: ['Project Management', 'Continuous Improvement', 'MS Office', 'Teamwork'],
        is_mentor: false,
        mentor_topics: [],
        photo_url: null,
        source: 'seed',
    },
];

export function getSeedAlumni(): Omit<AlumniProfile, 'id' | 'created_at' | 'updated_at'>[] {
    return SEED_ALUMNI.map(alumni => ({
        ...alumni,
        is_active: true,
    }));
}
