/**
 * Seed Data — Campus Events
 * 18 realistic events for Teknik Mesin ITS
 */

import type { CampusEvent } from './types';

type SeedEvent = Omit<CampusEvent, 'id' | 'created_at' | 'updated_at' | 'is_active'>;

export const SEED_EVENTS: SeedEvent[] = [
    {
        title: 'Seminar Nasional Energi Terbarukan 2026',
        description: 'Seminar yang membahas perkembangan terkini energi surya, angin, dan biomassa di Indonesia. Menghadirkan pembicara dari BRIN dan industri.',
        date_start: '2026-03-15',
        date_end: '2026-03-15',
        time_start: '08:00',
        time_end: '16:00',
        location: 'Auditorium Teknik Mesin ITS',
        organizer: 'Departemen Teknik Mesin ITS',
        category: 'seminar',
        status: 'rencana',
        budget: 15000000,
        expenditure: 0,
        max_participants: 300,
        registration_url: 'https://forms.gle/example1',
        image_url: null,
        contact_person: 'Dr. Ahmad Fauzi',
        source: 'seed',
    },
    {
        title: 'Workshop CAD/CAM & 3D Printing',
        description: 'Pelatihan intensif menggunakan SolidWorks dan Fusion 360, dilanjutkan praktik 3D printing. Sertifikat kompetensi diberikan.',
        date_start: '2026-02-22',
        date_end: '2026-02-23',
        time_start: '09:00',
        time_end: '17:00',
        location: 'Lab CAD/CAM Lt. 3',
        organizer: 'Himpunan Teknik Mesin',
        category: 'workshop',
        status: 'rencana',
        budget: 8000000,
        expenditure: 0,
        max_participants: 40,
        registration_url: 'https://forms.gle/example2',
        image_url: null,
        contact_person: 'Rizky Pratama',
        source: 'seed',
    },
    {
        title: 'Mechanical Engineering Design Competition 2026',
        description: 'Kompetisi desain mesin tingkat nasional. Tantangan: merancang mekanisme pengolahan sampah otomatis.',
        date_start: '2026-04-10',
        date_end: '2026-04-12',
        time_start: '07:00',
        time_end: '18:00',
        location: 'Gedung Riset ITS',
        organizer: 'BEM Teknik Mesin',
        category: 'lomba',
        status: 'rencana',
        budget: 25000000,
        expenditure: 0,
        max_participants: 100,
        registration_url: 'https://forms.gle/example3',
        image_url: null,
        contact_person: 'Siti Nurhaliza',
        source: 'seed',
    },
    {
        title: 'Rapat Kerja Himpunan Semester Genap',
        description: 'Rapat koordinasi seluruh pengurus himpunan untuk menyusun program kerja semester genap 2025/2026.',
        date_start: '2026-02-08',
        date_end: '2026-02-08',
        time_start: '13:00',
        time_end: '17:00',
        location: 'Ruang Sidang Dekanat',
        organizer: 'BPH Himpunan',
        category: 'rapat',
        status: 'selesai',
        budget: 500000,
        expenditure: 450000,
        max_participants: 50,
        registration_url: null,
        image_url: null,
        contact_person: 'Ketua Himpunan',
        source: 'seed',
    },
    {
        title: 'Bakti Sosial: Mengajar di Desa Binaan',
        description: 'Program pengabdian masyarakat di Desa Wonorejo. Mahasiswa mengajar sains dasar dan maintenance mesin pertanian.',
        date_start: '2026-03-01',
        date_end: '2026-03-02',
        time_start: '06:00',
        time_end: '18:00',
        location: 'Desa Wonorejo, Surabaya',
        organizer: 'Divisi Sosial Himpunan',
        category: 'sosial',
        status: 'rencana',
        budget: 5000000,
        expenditure: 0,
        max_participants: 30,
        registration_url: 'https://forms.gle/example5',
        image_url: null,
        contact_person: 'Dewi Sartika',
        source: 'seed',
    },
    {
        title: 'Turnamen Futsal Antar-Angkatan',
        description: 'Turnamen futsal tahunan untuk mempererat kebersamaan antar angkatan Teknik Mesin.',
        date_start: '2026-03-20',
        date_end: '2026-03-22',
        time_start: '15:00',
        time_end: '21:00',
        location: 'Lapangan Futsal ITS',
        organizer: 'Divisi Olahraga',
        category: 'olahraga',
        status: 'rencana',
        budget: 3000000,
        expenditure: 0,
        max_participants: 80,
        registration_url: null,
        image_url: null,
        contact_person: 'Budi Santoso',
        source: 'seed',
    },
    {
        title: 'Guest Lecture: Industry 4.0 & Smart Manufacturing',
        description: 'Kuliah tamu oleh VP Engineering PT Toyota Indonesia. Topik: transformasi digital di industri manufaktur.',
        date_start: '2026-02-28',
        date_end: null,
        time_start: '10:00',
        time_end: '12:00',
        location: 'Aula Teknik Mesin',
        organizer: 'Departemen Teknik Mesin',
        category: 'akademik',
        status: 'rencana',
        budget: 2000000,
        expenditure: 0,
        max_participants: 200,
        registration_url: 'https://forms.gle/example7',
        image_url: null,
        contact_person: 'Prof. Bambang',
        source: 'seed',
    },
    {
        title: 'Workshop Welding & Metal Fabrication',
        description: 'Pelatihan las MIG, TIG, dan SMAW di Lab Produksi. Peserta mendapat sertifikat keahlian.',
        date_start: '2026-03-08',
        date_end: '2026-03-09',
        time_start: '08:00',
        time_end: '16:00',
        location: 'Lab Produksi Teknik Mesin',
        organizer: 'Lab Teknik Produksi',
        category: 'workshop',
        status: 'rencana',
        budget: 12000000,
        expenditure: 0,
        max_participants: 25,
        registration_url: 'https://forms.gle/example8',
        image_url: null,
        contact_person: 'Pak Joko',
        source: 'seed',
    },
    {
        title: 'Exposure: Company Visit ke PT Semen Indonesia',
        description: 'Kunjungan industri ke pabrik PT Semen Indonesia di Gresik untuk melihat proses produksi dan maintenance.',
        date_start: '2026-04-05',
        date_end: null,
        time_start: '07:00',
        time_end: '17:00',
        location: 'PT Semen Indonesia, Gresik',
        organizer: 'Divisi Akademik',
        category: 'akademik',
        status: 'rencana',
        budget: 4000000,
        expenditure: 0,
        max_participants: 45,
        registration_url: 'https://forms.gle/example9',
        image_url: null,
        contact_person: 'Andi Wijaya',
        source: 'seed',
    },
    {
        title: 'Career Fair: Engineering Edition',
        description: 'Pameran karir khusus bidang engineering. 15+ perusahaan hadir: Toyota, Pertamina, PLN, Astra, dll.',
        date_start: '2026-04-20',
        date_end: '2026-04-21',
        time_start: '09:00',
        time_end: '16:00',
        location: 'Graha ITS',
        organizer: 'Himpunan + CDC ITS',
        category: 'umum',
        status: 'rencana',
        budget: 20000000,
        expenditure: 0,
        max_participants: 500,
        registration_url: 'https://forms.gle/example10',
        image_url: null,
        contact_person: 'Tim Career',
        source: 'seed',
    },
    {
        title: 'DIES NATALIS Teknik Mesin ke-56',
        description: 'Peringatan ulang tahun Departemen Teknik Mesin ITS. Acara: talkshow alumni, pentas seni, dan makan bersama.',
        date_start: '2026-05-10',
        date_end: '2026-05-10',
        time_start: '08:00',
        time_end: '22:00',
        location: 'Teknik Mesin ITS',
        organizer: 'Panitia DIES NATALIS',
        category: 'sosial',
        status: 'rencana',
        budget: 30000000,
        expenditure: 0,
        max_participants: 500,
        registration_url: null,
        image_url: null,
        contact_person: 'Panitia DIES',
        source: 'seed',
    },
    {
        title: 'Workshop Python untuk Engineer',
        description: 'Belajar Python untuk simulasi numerik, analisis data, dan otomasi CAD. Cocok untuk pemula.',
        date_start: '2026-02-15',
        date_end: '2026-02-16',
        time_start: '09:00',
        time_end: '15:00',
        location: 'Lab Komputer Lt. 2',
        organizer: 'Divisi IT Himpunan',
        category: 'workshop',
        status: 'berlangsung',
        budget: 3000000,
        expenditure: 1500000,
        max_participants: 30,
        registration_url: null,
        image_url: null,
        contact_person: 'Fauzan',
        source: 'seed',
    },
    {
        title: 'Seminar: Karir di Bidang Oil & Gas',
        description: 'Seminar dengan pembicara dari Pertamina dan Chevron tentang peluang karir di industri migas.',
        date_start: '2026-03-25',
        date_end: null,
        time_start: '13:00',
        time_end: '16:00',
        location: 'Aula Teknik Mesin',
        organizer: 'SPE ITS Student Chapter',
        category: 'seminar',
        status: 'rencana',
        budget: 5000000,
        expenditure: 0,
        max_participants: 150,
        registration_url: 'https://forms.gle/example13',
        image_url: null,
        contact_person: 'SPE ITS',
        source: 'seed',
    },
    {
        title: 'Pelatihan K3 (Keselamatan & Kesehatan Kerja)',
        description: 'Sertifikasi K3 Umum oleh Kemnaker. Wajib untuk mahasiswa yang akan magang di industri.',
        date_start: '2026-04-15',
        date_end: '2026-04-17',
        time_start: '08:00',
        time_end: '17:00',
        location: 'Ruang Kuliah Bersama',
        organizer: 'Departemen + Kemnaker',
        category: 'akademik',
        status: 'rencana',
        budget: 10000000,
        expenditure: 0,
        max_participants: 50,
        registration_url: 'https://forms.gle/example14',
        image_url: null,
        contact_person: 'Ibu Dian',
        source: 'seed',
    },
    {
        title: 'Mechanical Cup: Badminton & Table Tennis',
        description: 'Turnamen badminton dan tenis meja antar-departemen di lingkungan FTI ITS.',
        date_start: '2026-05-01',
        date_end: '2026-05-03',
        time_start: '14:00',
        time_end: '20:00',
        location: 'GOR ITS',
        organizer: 'Divisi Olahraga',
        category: 'olahraga',
        status: 'rencana',
        budget: 5000000,
        expenditure: 0,
        max_participants: 60,
        registration_url: null,
        image_url: null,
        contact_person: 'Abdul Rahman',
        source: 'seed',
    },
];

export function getSeedEvents(): Omit<CampusEvent, 'id' | 'created_at' | 'updated_at'>[] {
    return SEED_EVENTS.map(event => ({
        ...event,
        is_active: true,
    }));
}
