-- Migration: Align dimensions enum and seed Mental Health items
-- Generated by Antigravity

-- 1. Update dimension_type ENUM
-- Note: Postgres does not support removing enum values easily. 
-- We add the new values. value 'health', 'social', 'character' can be deprecated or mapped.
-- We map:
-- 'affective' -> 'self-management' (use new)
-- 'psychomotor' -> unused
-- 'health' -> 'physical' (use new)
-- 'social' -> 'emotional-social' (use new)
-- 'character' -> 'character-ethics' (use new)

DO $$
BEGIN
    ALTER TYPE dimension_type ADD VALUE IF NOT EXISTS 'self-management';
    ALTER TYPE dimension_type ADD VALUE IF NOT EXISTS 'physical';
    ALTER TYPE dimension_type ADD VALUE IF NOT EXISTS 'emotional-social';
    ALTER TYPE dimension_type ADD VALUE IF NOT EXISTS 'mental-health';
    ALTER TYPE dimension_type ADD VALUE IF NOT EXISTS 'character-ethics';
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 2. Seed Assessment Items for Mental Health (Dimension 6)
-- Source: DIMENSI 6.txt (Validated Instrument)

INSERT INTO public.assessment_instruments (dimension, question_text, question_order, framework_reference, level_indicator, weight) VALUES
('mental-health', 'Dalam sebulan terakhir, seberapa sering Anda merasa bahagia?', 1, 'MHC-SF (Keyes, 2009) - Emotional Wellbeing', 3, 1.2),
('mental-health', 'Saya dapat beradaptasi dengan baik ketika menghadapi perubahan atau kesulitan', 2, 'CD-RISC-10 - Resilience', 3, 1.3),
('mental-health', 'Dalam sebulan terakhir, seberapa sering Anda merasa tidak mampu mengatasi semua hal yang harus Anda lakukan? (Reverse Scored)', 3, 'PSS-4 - Stress Management', 2, 1.4),
('mental-health', 'Saya mengalami peristiwa dengan penuh kesadaran, tanpa terdistraksi atau "autopilot"', 4, 'MAAS - Mindfulness', 3, 1.1),
('mental-health', 'Saya dapat mengelola emosi dan kenangan masa lalu yang sulit dengan cara yang sehat', 5, 'Inner Child Healing Scale - Trauma', 4, 1.2),
('mental-health', 'Beban akademik (tugas, ujian, proyek) sering membuat saya merasa kewalahan (Reverse Scored)', 6, 'Academic Stress', 2, 1.3),
('mental-health', 'Saya memiliki strategi yang efektif untuk mengatasi kesulitan atau masalah', 7, 'Brief COPE - Coping Strategies', 3, 1.1),
('mental-health', 'Saya merasa nyaman mencari bantuan profesional (konselor, psikolog) ketika mengalami kesulitan emosional', 8, 'Mental Help Seeking Attitudes', 2, 1.0);

-- 3. Update existing records if needed (Optional / Caution)
-- UPDATE public.assessment_instruments SET dimension = 'physical' WHERE dimension = 'health';
-- UPDATE public.assessment_instruments SET dimension = 'emotional-social' WHERE dimension = 'social';
-- UPDATE public.assessment_instruments SET dimension = 'character-ethics' WHERE dimension = 'character';
